#!/usr/bin/python3


import argparse
from os import uname
import os
import time
import pathlib
import sys
import requests

print("GetPlugin v0.0.1")



pl = "/etc/rcbash/plugins.txt"
repos = []
branch = "master"

def loadrep(f):
    c = open(f)

    for i in c.readlines():
        if i.strip().startswith("//"):
            continue
        if len(i.strip()) > 0:
            repos.append(i.strip())

parser = argparse.ArgumentParser("GetPlugin")

subp = parser.add_subparsers()

get = subp.add_parser("get", help="Get a plugin")

get.add_argument("PLUGIN_NAME", help="The plugin to install.")
get.add_argument("-uc", help="check this to use a custom plugins.txt file.")
get.add_argument("-c", help="Use a custom plugins.txt file. This is for Custom plugins, should be a github repo (raw user content)")
get.add_argument("-f", help="DEBUG mode (to see operations live).", action="store_true")
get.add_argument("-branch", default="master", help="This is the branch used for rawusercontent. This is not recommended to change.")

args = parser.parse_args()

branch = args.branch

global vn

try:
    vn = args.PLUGIN_NAME
except:
    parser.print_help()

print("Installing {}...".format(vn))

if (args.uc == True):
    pl = args.c

if (args.f):
    print("Checking integrity of plugins.txt from {}.".format(pl))

if pathlib.Path(pl).exists():
    if (args.f):
        print("Loading repositories.")
    loadrep(pl)
    fond = False
    
    print("d")
    if (args.f):
        print("Repository check: {}{}/{}.py".format(repos[0], args.PLUGIN_NAME, args.PLUGIN_NAME))
    l = "{}{}/{}.py".format(repos[0], args.PLUGIN_NAME, args.PLUGIN_NAME)
    p = requests.get(l)
    if p.status_code == 404:
        if args.f:
            print("Couldn't locate in {}".format(repos[0]))
    else:
        fond = True
        print("located, installing...")
        print("saving...")
        os.mkdir('/etc/rcbash/Plugins/{}'.format(args.PLUGIN_NAME))
        i = open("/etc/rcbash/Plugins/{}/{}.py".format(args.PLUGIN_NAME, args.PLUGIN_NAME), 'w')
        i.write(p.text)
        i.close()
    time.sleep(1)
        
else:
    if not pathlib.Path("setup").exists() :
        os.mkdir("setup")
    p = open("setup/plugins.txt", "w")
    p.write("""
// This is the plugins.txt file. You can write comments
// using the '//' operator.
// Blank lines are a bad practice and undefined behaviour. 
// These are trusted sources (from the official RCBash developer.)
// This is the first and only should be URL.

// You can't use any more URLs, you can only change it to install new ones and change it back.
https://raw.githubusercontent.com/thekaigonzalez/RCBash/master/local-repo/
    """)
    p.close()
    print("error: could not find plugins.txt.")
    print("Don't panic! I've created a sample plugins.txt in the local 'setup' directory.")
    if sys.platform == "win32":
        print("Run the command 'copy setup\\plugins.txt C:\\rcbash\\plugins.txt'")
    elif sys.platform == "linux":
        print("Run the command 'sudo cp ./setup/plugins.txt /etc/rcbash/plugins.txt'")