#!/usr/bin/python3

# Copyright 2022 kaigonzalez
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import pathlib
import sys

import argparse

parser = argparse.ArgumentParser()

parser.add_argument("FILE", help="File to execute.")
parser.add_argument("-append", help="append A directory to lib for std:lib candidates", default=None)
parser.add_argument("-lib", help="Version of ReConfiguration to use, if not specified, it will not work correctly (UNLESS YOU HAVE IT ON PATH)", default=None)

args = parser.parse_args()

rcfg_version = ""

if (args.lib != None):
    sys.path.append(args.lib)
    import RCScript.RCReConfig as rcfg
else:
    print("Warning: lib not specified")
    
import RCScript.RCReConfig as rcfg

if pathlib.Path(args.FILE).exists():
    f = open(args.FILE, "r")
    if args.append != None:
        sys.path.append(args.append)
    rcfg.rcfg_rstatstring(f.read())